---
title: "Forever Functional: Waiting For Some Promises"
date: 2024-02-10
category: "Javascript"
---

## Forever Functional: Waiting For Some Promises?

이 글은 필자가 잠재적인 개발자를 인터뷰할 때 가끔 제기하는 프로그래밍 문제로 시작하겠습니다. 도시 이름을 수락하고 현재 온도를 반환하는 서비스를 작성하라는 메시지가 표시됩니다. 이를 위해 세 개의 타사 날씨 API를 호출하고 하나의 답변을 받는 즉시 회신할 수 있습니다. 어떻게 해야 할까요?

JavaScript의 promise [동시성 메서드를](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#promise_concurrency) 알고 있다면 각 날씨 API를 호출하는 promise를 생성하고 [`Promise.any()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any)를 사용하여 이행된 첫 번째 promise에서 필요한 값을 가져오는 것은 쉽습니다.

변형: _모든_ 날씨 API가 응답할 때까지 기다렸다가 세 가지 온도의 평균으로 응답하도록 요청했다면 어땠을까요? 또한 쉽습니다 : [`대신 Promise.all()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) 을 사용했을 것입니다.

이제 _두 개의 날씨_ API가 응답할 때까지 기다렸다가 두 온도의 평균을 반환하도록 요청했다면 어땠을까요? 이에 대한 방법은 없습니다. 우리는 당신이 일련의 약속 중 일부를—하나도 아니고 전부도 아닌—기다릴 수 있게 해 줄 것이 필요하며, 이것이 바로 이 기사에서 우리가 할 일입니다.`Promise.some()`

## 새로운 방법 계획하기

메서드 코딩을 시작하기 전에 다음 두 가지 질문에 답해야 합니다.`Promise.some()`

- 이 메서드의 매개 변수는 무엇이어야합니까?
- 메서드는 무엇을 반환해야 합니까?

둘 다 약속의 반복 가능 항목을 (유일한) 매개 변수로 사용하므로 첫 번째 매개 변수가되어야합니다. 얼마나 많은 약속을 이행해야 하는지 지정하기 위해 두 번째 약속이 필요하므로 다음을 보고 있습니다. 쉬운!` Promise.any()``Promise.all()``Promise.some(promisesArray, fulfilledCount) `

두 번째 질문에 대해 몇 가지 분석을 수행해 보겠습니다.

- `Promise.any()` 배열의 약속 중 하나가 이행되면 이행되고 모든 약속이 거부되면 거부됩니다. 이행될 때 반환되는 값은 이행된 약속이 반환한 값이며, 거부되면 모든 거부 이유와 함께 반환됩니다.`AggregateError`
- `Promise.all()` 배열의 모든 약속이 이행되면 충족되고 해당 약속 중 하나만 거부되면 거부됩니다. 충족될 때 반환된 값은 충족된 모든 값이 있는 배열이며, 거부될 때 첫 번째 거부 이유와 함께 오류를 반환합니다.
- 두 방법 모두 단락 평가를 적용합니다: 약속이 이행되는 즉시 이행되고 약속이 거부되는 즉시 거부됩니다.` Promise.any()``Promise.all() `

이제 우리는 약속이 이행되면 이행되고 그렇지 않으면 거부되는 것을 정의 할 수 있습니다. 이행될 때 반환된 값은 이행된 약속에 의해 반환된 값이 있는 배열이며, 거부되면 거부된 약속에 대한 이유와 함께 an을 반환합니다.` Promise.some(promises, count)``count``AggregateError `

우리는 또한 단락 평가(short-circuit evaluation)를 해야 한다: 충분한 약속이 성취되는 순간 이행되어야 하고, 너무 많은 약속이 거부되어 충분한 약속이 이행되는 것이 불가능해지면 거부되어야 한다.`Promise.some()`

이 정의는 와 정확히 동일합니다. 다른 한편으로는, 같지 않을 것입니다 — 차이점은 fulfilled 는 single을 반환하지만 값 배열을 반환한다는 것입니다. 이 경우 하나.` Promise.some(promises, promises.length)``Promise.all(promises)``Promise.some(promises, 1)``Promise.any(promises)``.any()``.some() `

## 새로운 방법 코딩

이제 우리가 원하는 것이 무엇인지 알았으니 구현하는 방법을 살펴 보겠습니다. 이미 객체를 수정하여 시작할 수 있습니다.`Promise.prototype`

```javascript
Promise.some = function (promises, count) {
  return promiseSome(promises, count);
};
```

(일반적으로 해서는 안 되는 전역 개체를 수정하고 싶지 않다면 어떻게 해야 할까요? 이 경우 기능을 직접 사용하면 모든 것이 작동합니다.)`promiseSome()`

분명히, 작은 세부 사항이 있습니다 — 기능은 무엇입니까? 배열의 모든 약속에서 새 약속을 만들어야 합니다. 우리는 또한 그들이 해결하거나 거부하는 개별 약속을 추적해야 합니다. 새 약속은 개별 약속이 충분히 해결되거나 거부된 경우에만 해결되거나 거부됩니다. 이 코드는 다음을 수행합니다.`promiseSome()`

```javascript
    function promiseSome(promises, count) {                        // (1)
      return new Promise((resolve, reject) => {                    // (2)
        const resolved = [];                                       // (3)
        const rejected = [];                                       // (4)

        promises.forEach((promise, index) => {                     // (5)
          promise
            .then((val) => {
              resolved.push(val);                                  // (6)
              if (resolved.length === count) {
                resolve(resolved);                                 // (7)
              }
            })
            .catch((err) => {
              rejected.push(err);                                  // (8)
              if (rejected.length > promises.length - count) {
                reject(new AggregateError(rejected));              // (9)
              }
            });
        });
      });
```

이것이 어떻게 작동하는지 분석해 보겠습니다. 배열에는 해결하려는 모든 개별 입력 약속이 있습니다 (1). 입력 약속이 수행하는 작업에 따라 해결되거나 거부되는 새 약속(2)을 만듭니다. 우리는 약속이 해결되거나 거부 될 때 약속의 결과에 대해 두 개의 배열 (3)과 (4)를 사용합니다. 각 promise(5)에 대해 해결되면 결과를 배열(6)에 저장하고 충분한 promise가 해결되면 배열(7)로 새 promise를 해결합니다.` promises``count``resolved``rejected``resolved``resolved `

개별 promise가 거부되면 비슷한 작업을 수행하지만 거부 이유를 배열(8)에 저장합니다. 너무 많은 약속이 거부된 경우(해결된 약속을 달성하는 것이 불가능함) 일련의 이유와 함께 새 약속을 거부합니다(9). 우리는 끝났습니다!` rejected``count``AggregateError `

### 개발자를 위한 세션 재생

좌절감을 발견하고, 버그를 이해하고, 이전과는 전혀 다른 방식으로 속도 저하를 수정하십시오. [오픈리플레이](https://github.com/openreplay/openreplay) — 개발자를 위한 오픈 소스 세션 재생 도구. 몇 분 안에 자체 호스팅하고 고객 데이터를 완벽하게 제어할 수 있습니다. [GitHub 리포지토리 확인](https://github.com/openreplay/openreplay) 커뮤니티의 수천 명의 개발자와 함께하세요.

## 새로운 방법 테스트

이를 테스트하려면 몇 가지 가짜 약속이 필요합니다.

```javascript
    const success = (time, value) =>
      new Promise((resolve) => setTimeout(resolve, time, value));

    const failure = (time, reason) =>
      new Promise((_, reject) => setTimeout(reject, time, reason));

우리 함수는 일정 시간이 지나면 주어진 . 마찬가지로, 이 함수는 시간이 지나면 . 이러한 기능을 사용하여 몇 가지 검사를 실행할 수 있으며, 원하는 경우 Jest로 직접 바뀔 수 있습니다.` success()``value``failure()``reason `

    Promise.some([success(2000, 1), success(1500, 2), success(500, 3)], 2).then(
      (r) => console.log("Test #1: Should succeed with 2 and 3", r)
    );

    Promise.some([success(2100, 4), failure(400, 5), success(600, 6)], 1).then(
      (r) => console.log("Test #2: Should succeed with 6", r)
    );

    Promise.some([success(2200, 7), failure(300, 8), success(700, 9)], 3).catch(
      (r) => console.log("Test #3: Should reject with 8", r)
    );

    Promise.some([success(900, 10), failure(1800, 11), failure(800, 12)], 2).catch(
      (r) => console.log("Test #4: Should reject with 11 and 12", r)
    );
```

이를 실행하면 다음과 같은 결과가 생성됩니다.

```javascript
    Test #3: Should reject with 8 AggregateError {
      [errors]: [ 8 ]
    }
    Test #2: Should succeed with 6 [ 6 ]
    Test #1: Should succeed with 2 and 3 [ 3, 2 ]
    Test #4: Should reject with 11 and 12 AggregateError  {
      [errors]: [ 12, 11 ]
    }
```

확인해보자.

- 테스트 #3은 300ms에 실패하며, 충분한 약속을 해결할 수 없다는 것이 분명합니다.
- 테스트 #2는 400ms에 이미 실패했음에도 불구하고 단일 promise가 해결될 때 600ms에 성공합니다.
- 다음은 테스트 #1입니다. 시간 1500ms에서 두 가지 약속이 해결됩니다.
- 테스트 #4는 1800ms에서 두 번째 거부를 받을 때 마지막입니다.

더 많은 기능으로 더 많은 테스트를 수행할 수 있지만 올바른 방향으로 가고 있는 것 같고 방법이 원하는 방식으로 작동하고 있습니다.`Promise.some()`

## 메서드 입력

TypeScript를 사용하는 경우 몇 가지 흥미로운 세부 정보가 있는 몇 가지 입력을 정의해야 합니다. 먼저, TypeScript가 using 을 허용하도록 해야 하며, 에 입력을 추가할 수 있습니다.` npm install aggregate-error``AggregateError()``promiseSome() `

```javascript
    function promiseSome(promises: Promise<any>[], count: number): Promise<any[]> {
      return new Promise((resolve, reject) => {
        const resolved: any[] = [];
        const rejected: any[] = [];

        promises.forEach((promise, index) => {
            .
            .
            .
        });
      });
    }
```

타입은 간단합니다: 우리는 모든 타입과 숫자의 promise의 배열을 얻고, promise의 배열로 해석되는 promise를 생성합니다. and 배열은 모든 유형을 가질 수 있으므로 복잡하지 않습니다. 그러나 전역 개체를 수정하려는 경우 문제가 있습니다. 이 솔루션을 사용하려면 다음과 같이 [`PromiseConstructor` 인터페이스](https://github.com/microsoft/TypeScript/blob/main/lib/lib.es2015.promise.d.ts)에 정의를 추가해야 합니다.` resolved``rejected``Promise `

```javascript
    declare global {
      interface PromiseConstructor {
        some(promises: Promise<any>[], count: number): Promise<any[]>;
      }
    }
```

우리는 이제 모든 약속에도 추가 방법이 있을 것이며 다음을 수행할 수 있다고 말하고 있습니다.`some()`

```javascript
Promise.some = function (promises: Promise<any>[], count: number) {
  return promiseSome(promises, count);
};
```

테스트를 다시 실행하려면 가짜 약속을 입력해야 하지만 어렵지 않습니다. 다음과 같이 type 매개 변수에 따라 두 개의 일반 함수가 있습니다.`T`

```javascript
const success = <T>(time: number, value: T): Promise<T> =>
  new Promise((resolve) => setTimeout(resolve, time, value));

const failure = <T>(time: number, reason: T): Promise<T> =>
  new Promise((_, reject) => setTimeout(reject, time, reason));
```

이제 끝났어요!

## 결론

이 문서에서는 여러 promise를 처리하는 것과 관련된 문제를 확인했으며 이를 해결하기 위해 개체를 promise하는 새로운 메서드를 추가하여 여러 사례로 테스트했습니다. 완성도를 높이기 위해 어디서나 사용할 수 있도록 코드를 TypeScript로 변환하는 방법도 살펴보았습니다. 모든 면에서 승리!

출처: [https://blog.openreplay.com/forever-functional-waiting-for-some-promises/](https://blog.openreplay.com/forever-functional-waiting-for-some-promises/)
